### ISSUE TITLE
Various .dll files missing

### ISSUE THREAD

**Issue by MatthewHinds** [Miyuyami/MS2Tools#2]
Building the solution after checking out each library and re-constructing the reference as laid out in the main MS2Tools, I am getting missing .dll files errors.

[Image of build errors](https://i.imgur.com/PYi5mIl.png)

Thank you and please let me know if there's anything I'm doing incorrectly.

**Comment by Miyuyami** [comment]
You have to first build the C++ separately. (Decrypt C++ Project)
Go to batch build and build them. https://i.imgur.com/bmO01Lp.png

**Comment by MatthewHinds** [comment]
Thanks for the reply Miyuyami,

I went ahead and batch built the Decrypt project, but I'm encountering these issues.

Am I missing a package or reference perhaps?

[Errors](https://i.imgur.com/QqGMoIu.png)

**Comment by Miyuyami** [comment]
You have to get CryptoPP on your own, it's part of MS2Lib, the readme is on that specific repository as well: https://github.com/Miyuyami/MS2Lib/blob/master/README.md

**Comment by MatthewHinds** [comment]
Hi Miyuyami,

Thank you for the response.

However this has brought me even more question as the readme is not very clear.

> You need CryptoPP.

(I downloaded this, installed Windows 8.1 SDK and Windows 10 UCRT)
> Build the libraries as "*.lib" and name as following (NOTE: you can change those in "stdafx.h"):

(What libraries are you referring too? MS2Lib or CryptoPP?. Also what do you mean "build as *.lib".
I checked "stdafx.h" on MS2Lib and can see you're referencing the CryptoPP. But how are you targetting it?)


> Change "IncludePath", "LibraryPath" and "SourcePath" to the path where you have all those 4 libs.

(Again, where is this? CryptoPP or MS2Lib?)
> In the same path also add all includes (main folder of CryptoPP with all headers).

(Can you give an example)
> Now "Decrypt" project should successfuly build.


Essentially would it be possible to have a detailed step by step process in building this with CryptoPP. I understand that this may be quite easy for you, however I'm completely unsure on how you're setting this all up. Thank you again and I appreciate your work in this.

**Comment by Miyuyami** [comment]
You can do it in your own way if you want, that's just the simplest way I got it to work.

The .lib files are from CryptoPP, they are linked when building the C++ project dlls (Decrypt32.dll and Decrypt64.dll). You have to build the .lib files from the CryptoPP project that you said you downloaded.
You build multiple libs and name the accordingly:
* "cryptlib" for Release 32 bit
* "cryptlib_x64" for Release 64 bit
* "cryptlibd" for Debug 32 bit
* "cryptlibd_x64" for Debug 64 bit

Now place all those 4 files in the root folder where all *.h files of the CryptoPP project are, let's say it's `C:\CryptoPP`. It should look something like this: https://i.imgur.com/dNqJqmH.png

Now you go into the Decrypt C++ project and you have to set up the paths to that folder, so it knows what to link and include.

1. You do that by going to the project options (Menu -> Project -> Decrypt Properties) and under `Configuration Properties` you go to `VC++ Directories`.
2. Now select for `Configuration: All Configurations` and for `Platform: All Platforms`.
3. Now in `Include Directories`, `Library Directories` and `Source Directories` you put the path from before, which in my example is `C:\CryptoPP`

Since those should still have my own settings, they are all set to `C:\Games\RANDOM\C++\Cryptopp\trunk\c5` so you just have to replace that.

**Comment by MatthewHinds** [comment]
Hi Miyuyami,

Thank you so much. That helped a lot and made quite a lot of sense! Those were really great instructions and it helped me get through this stage with ease.

Just one last issue I'm encountering. Though please note that I'm completely unaware of C++, so I'm not too familiar with it at all.

However I'm encountering the following issues when attempting to batch build the 'Decrypt' project.

https://i.imgur.com/urwKoYK.png

What would be your recommended solution for this?

Thank you again for all your help!

**Comment by Miyuyami** [comment]
I don't know, I don't use C++ at all either.
Try googling around for answers, it's probably something related to your compilers.
