### ISSUE TITLE
Repacking Issue

### ISSUE THREAD

**Issue by she40841** [Miyuyami/MS2Tools#3]
First, thanks for these utilities! Compiled and having no problems extracting, but using MS2Create always throws

`[Error] [11/10/2018 12:02:15 AM] System.AggregateException: One or more errors occurred. ---> System.EntryPointNotFoundException: Unable to find an entry point named 'Delete' in DLL 'Decrypt64.dll'.`

This happens pretty much immediately, unsurprisingly. Any suggestions?

**Comment by Miyuyami** [comment]
Does this only happen when you build it yourself? Does the same thing happen when you use the provided binaries in https://github.com/Miyuyami/MS2Tools/releases?
If it only happens when you build it yourself, did you make sure to build the Decrypt project dlls in the same folder as MSCreate executable? You can check this in the build folders if Decrypt64.dll is present.

**Comment by she40841** [comment]
Sorry for the late reply, it was entirely my bad. Didn't compile it correctly, your work is perfect. Thank you again for the util!
